name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ROS 2 workspace
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build
          colcon test
          colcon test-result

      - name: Run custom test script
        run: |
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

