name: test

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS 2 environment
        run: |
          source /opt/ros/humble/setup.bash
          source /root/ros2_ws/install/setup.bash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-rosdep
          sudo rosdep init
          rosdep update
          cd /root/ros2_ws
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          cd /root/ros2_ws
          colcon build --symlink-install
          source /root/ros2_ws/install/setup.bash

      - name: Test package
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root
          
      - name: Check test results
        run: |
          cat /tmp/mypkg.log | grep 'User CPU'

